# NumPy Notebook

NumPy is a Python library used for fast numerical calculations.

In this notebook, we will use one consistent Indian example: monthly sales of stores in Indian cities.

Topics covered:
- Creating arrays
- Array properties
- Indexing and slicing
- Vectorized operations
- Aggregation functions
- Boolean filtering
- 2D arrays
- Axis logic
- Broadcasting
- Reshaping
- Useful NumPy functions


In [29]:
!pip install numpy

You should consider upgrading via the '/Users/rama/Desktop/BITSoM_Batch3/.venv/bin/python3 -m pip install --upgrade pip' command.


In [30]:
import numpy as np


## 1. Create a NumPy Array

A NumPy array is like a Python list, but it is faster for numerical work.

Here we store monthly sales, in rupees, for one store.


In [36]:
L=[120000, 150000, 135000, 170000, 160000.1, 180000]
monthly_sales = np.array(L)
monthly_sales


array([120000. , 150000. , 135000. , 170000. , 160000.1, 180000. ])

In [34]:
print(type(monthly_sales))

<class 'numpy.ndarray'>


In [38]:
print(monthly_sales.dtype)

float64


In [39]:
new_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
new_2d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
new_2d_array.shape

(2, 3)

In [41]:
new_2d_array.size

6

In [42]:
new_2d_array.ndim

2

## 2. Array Properties

These properties help us understand the structure of an array.


In [52]:
L=[120000, 150000, 135000, 170000, 160000.1, 180000]
monthly_sales = np.array(L)
monthly_sales

array([120000. , 150000. , 135000. , 170000. , 160000.1, 180000. ])

In [53]:
print("Shape:", monthly_sales.shape)
print("Size:", monthly_sales.size)
print("Dimensions:", monthly_sales.ndim)
print("Data type:", monthly_sales.dtype)


Shape: (6,)
Size: 6
Dimensions: 1
Data type: float64


In [28]:
type(monthly_sales)

numpy.ndarray

## 3. Indexing

Indexing is used to select one value from an array. Python indexing starts from 0.


In [54]:
print("First month sales:", monthly_sales[0])
print("Third month sales:", monthly_sales[2])
print("Last month sales:", monthly_sales[-1])


First month sales: 120000.0
Third month sales: 135000.0
Last month sales: 180000.0


## 4. Slicing

Slicing is used to select a range of values.


In [55]:
print("First three months:", monthly_sales[0:3])
print("From fourth month onwards:", monthly_sales[3:6])
print("Alternate months:", monthly_sales[::2])


First three months: [120000. 150000. 135000.]
From fourth month onwards: [170000.  160000.1 180000. ]
Alternate months: [120000.  135000.  160000.1]


## 5. Vectorized Operations

NumPy can perform calculations on the whole array at once.


In [56]:
monthly_sales

array([120000. , 150000. , 135000. , 170000. , 160000.1, 180000. ])

In [66]:
for i in range(6):
    print(monthly_sales[i]+10000)

130000.0
160000.0
145000.0
180000.0
170000.1
190000.0


In [69]:
# Add Rs. 10,000 to every month
monthly_sales=monthly_sales + 10000
print(monthly_sales)


[130000.  160000.  145000.  180000.  170000.1 190000. ]


In [71]:
# Convert rupees to lakhs
monthly_sales / 100000


array([1.3     , 1.6     , 1.45    , 1.8     , 1.700001, 1.9     ])

In [72]:
# Increase every month's sales by 10 percent
monthly_sales * 1.10


array([143000.  , 176000.  , 159500.  , 198000.  , 187000.11, 209000.  ])

## 6. Aggregation Functions

Aggregation functions summarize data.


In [ ]:
print("Total sales:", monthly_sales.sum())
print("Average sales:", monthly_sales.mean())
print("Minimum sales:", monthly_sales.min())
print("Maximum sales:", monthly_sales.max())

Total sales: 915000
Average sales: 152500.0
Minimum sales: 120000
Maximum sales: 180000


In [73]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [74]:
array_2d.sum()

np.int64(21)

In [75]:
array_2d.sum(axis=0)

array([5, 7, 9])

In [76]:
array_2d.sum(axis=1)

array([ 6, 15])

## 7. Boolean Filtering

Boolean filtering selects values that match a condition.


In [78]:
monthly_sales

array([130000. , 160000. , 145000. , 180000. , 170000.1, 190000. ])

In [79]:
condition=monthly_sales > 150000
condition


array([False,  True, False,  True,  True,  True])

In [80]:
monthly_sales[condition]


array([160000. , 180000. , 170000.1, 190000. ])

## 8. 2D Arrays

A 2D array is like a table.

Here, rows are Indian cities and columns are months.


In [81]:
cities = np.array(["Mumbai", "Delhi", "Bengaluru"])
months = np.array(["Jan", "Feb", "Mar", "Apr"])

city_sales = np.array([
    [120000, 150000, 135000, 170000],
    [100000, 125000, 140000, 155000],
    [130000, 160000, 150000, 190000]
])

city_sales


array([[120000, 150000, 135000, 170000],
       [100000, 125000, 140000, 155000],
       [130000, 160000, 150000, 190000]])

In [82]:
print("Shape:", city_sales.shape)
print("Rows:", city_sales.shape[0])
print("Columns:", city_sales.shape[1])


Shape: (3, 4)
Rows: 3
Columns: 4


## 9. Selecting Data from a 2D Array

Use row index and column index to select values from a 2D array.


In [83]:
# Sales of Mumbai across all months
city_sales[0]


array([120000, 150000, 135000, 170000])

In [84]:
# Sales of all cities in February
city_sales[:, 1]


array([150000, 125000, 160000])

In [85]:
# Sales of Delhi in March
city_sales[1, 2]


np.int64(140000)

## 10. Axis Logic

- `axis=0` works down the rows, giving column-wise results.
- `axis=1` works across the columns, giving row-wise results.


In [86]:
# Total sales for each month
city_sales.sum(axis=0)


array([350000, 435000, 425000, 515000])

In [87]:
# Total sales for each city
city_sales.sum(axis=1)


array([575000, 520000, 630000])

In [88]:
# Average sales for each city
city_sales.mean(axis=1)


array([143750., 130000., 157500.])

## 11. Reshaping

Reshaping changes the shape of an array without changing its values.


In [91]:
numbers = np.arange(1, 13)
numbers


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [95]:
A=numbers.reshape(3, 4)
A


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
numbers.reshape(2, 6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])