# NumPy Notebook

NumPy is a Python library used for fast numerical calculations.

In this notebook, we will use one consistent Indian example: monthly sales of stores in Indian cities.

Topics covered:
- Creating arrays
- Array properties
- Indexing and slicing
- Vectorized operations
- Aggregation functions
- Boolean filtering
- 2D arrays
- Axis logic
- Broadcasting
- Reshaping
- Useful NumPy functions


In [ ]:
!pip install numpy

In [1]:
import numpy as np


## 1. Create a NumPy Array

A NumPy array is like a Python list, but it is faster for numerical work.

Here we store monthly sales, in rupees, for one store.


In [2]:
monthly_sales = np.array([120000, 150000, 135000, 170000, 160000, 180000])
monthly_sales


array([120000, 150000, 135000, 170000, 160000, 180000])

## 2. Array Properties

These properties help us understand the structure of an array.


In [3]:
print("Shape:", monthly_sales.shape)
print("Size:", monthly_sales.size)
print("Dimensions:", monthly_sales.ndim)
print("Data type:", monthly_sales.dtype)


Shape: (6,)
Size: 6
Dimensions: 1
Data type: int64


## 3. Indexing

Indexing is used to select one value from an array. Python indexing starts from 0.


In [4]:
print("First month sales:", monthly_sales[0])
print("Third month sales:", monthly_sales[2])
print("Last month sales:", monthly_sales[-1])


First month sales: 120000
Third month sales: 135000
Last month sales: 180000


## 4. Slicing

Slicing is used to select a range of values.


In [5]:
print("First three months:", monthly_sales[0:3])
print("From fourth month onwards:", monthly_sales[3:])
print("Alternate months:", monthly_sales[::2])


First three months: [120000 150000 135000]
From fourth month onwards: [170000 160000 180000]
Alternate months: [120000 135000 160000]


## 5. Vectorized Operations

NumPy can perform calculations on the whole array at once.


In [6]:
# Add Rs. 10,000 to every month
monthly_sales + 10000


array([130000, 160000, 145000, 180000, 170000, 190000])

In [7]:
# Convert rupees to lakhs
monthly_sales / 100000


array([1.2 , 1.5 , 1.35, 1.7 , 1.6 , 1.8 ])

In [8]:
# Increase every month's sales by 10 percent
monthly_sales * 1.10


array([132000., 165000., 148500., 187000., 176000., 198000.])

## 6. Aggregation Functions

Aggregation functions summarize data.


In [9]:
print("Total sales:", monthly_sales.sum())
print("Average sales:", monthly_sales.mean())
print("Minimum sales:", monthly_sales.min())
print("Maximum sales:", monthly_sales.max())


Total sales: 915000
Average sales: 152500.0
Minimum sales: 120000
Maximum sales: 180000


## 7. Boolean Filtering

Boolean filtering selects values that match a condition.


In [10]:
monthly_sales > 150000


array([False, False, False,  True,  True,  True])

In [11]:
monthly_sales[monthly_sales > 150000]


array([170000, 160000, 180000])

## 8. 2D Arrays

A 2D array is like a table.

Here, rows are Indian cities and columns are months.


In [13]:
cities = np.array(["Mumbai", "Delhi", "Bengaluru"])
months = np.array(["Jan", "Feb", "Mar", "Apr"])

city_sales = np.array([
    [120000, 150000, 135000, 170000],
    [100000, 125000, 140000, 155000],
    [130000, 160000, 150000, 190000]
])

city_sales


array([[120000, 150000, 135000, 170000],
       [100000, 125000, 140000, 155000],
       [130000, 160000, 150000, 190000]])

In [14]:
print("Shape:", city_sales.shape)
print("Rows:", city_sales.shape[0])
print("Columns:", city_sales.shape[1])


Shape: (3, 4)
Rows: 3
Columns: 4


## 9. Selecting Data from a 2D Array

Use row index and column index to select values from a 2D array.


In [15]:
# Sales of Mumbai across all months
city_sales[0]


array([120000, 150000, 135000, 170000])

In [16]:
# Sales of all cities in February
city_sales[:, 1]


array([150000, 125000, 160000])

In [17]:
# Sales of Delhi in March
city_sales[1, 2]


np.int64(140000)

## 10. Axis Logic

- `axis=0` works down the rows, giving column-wise results.
- `axis=1` works across the columns, giving row-wise results.


In [18]:
# Total sales for each month
city_sales.sum(axis=0)


array([350000, 435000, 425000, 515000])

In [19]:
# Total sales for each city
city_sales.sum(axis=1)


array([575000, 520000, 630000])

In [20]:
# Average sales for each city
city_sales.mean(axis=1)


array([143750., 130000., 157500.])

## 11. Reshaping

Reshaping changes the shape of an array without changing its values.


In [23]:
numbers = np.arange(1, 13)
numbers


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
numbers.reshape(3, 4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
numbers.reshape(2, 6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])